kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data-claim
  annonations:
    volume.beta.kubernets.io/storage-class: default-sc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
