kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-client-claim
  annonations:
    volume.beta.kubernetes.io/storage-class: default-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
