apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master
  labels:
    type: local
spec:
  storageClassName: mytest-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
