name: Deploy Node.js App with Agentic AI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_VM_HOST }}
          username: ${{ secrets.GCE_VM_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd ~/agenticai-demo
            git pull origin master
            npm install
            pkill node || true

            # Start app in background
            nohup node app.js > app.log 2>&1 &

            # Wait briefly
            sleep 3

            # Check for failure
            if grep -q "Error:" app.log; then
              echo "🚨 App failed to start."

              echo "🤖 Running Agentic AI recovery..."
              export AGENTIC_AI_ENABLED=true
              export AUTO_FIX_ENABLED=true
              export PYTHONPATH=$PYTHONPATH:$(pwd)
              python3 AgenticAI/agentic_ai_runner.py

              echo "🔁 Rechecking logs..."
              pkill node || true
              sleep 1
              nohup node app.js > app.log 2>&1 &
              sleep 3

              if grep -q "Error:" app.log; then
                echo "❌ Agentic AI failed to recover the app."
                exit 1
              else
                echo "✅ Agentic AI successfully recovered the app."
              fi
            else
              echo "✅ App started successfully."
            fi
